Islandora/Crayfish

src/ResourceService/Controller/ResourceController.php
See: https://github.com/Islandora-CLAW/CLAW/issues/302 and https://github.com/Islandora-CLAW/chullo/pull/51
=> Address https://github.com/Islandora-CLAW/CLAW/issues/302

.travis.yml, Gemini/.gitignore, Gemini/README.md, Gemini/cfg/cfg.php, Gemini/composer.json, Gemini/phpunit.xml.dist, Gemini/src/Controller/GeminiController.php, Gemini/src/Service/GeminiService.php, Gemini/src/Service/GeminiServiceInterface.php, Gemini/src/app.php, Gemini/src/index.php, Gemini/tests/Islandora/Gemini/Tests/CreatePairTest.php, Gemini/tests/Islandora/Gemini/Tests/DeleteFromDrupalPathTest.php, Gemini/tests/Islandora/Gemini/Tests/DeleteFromFedoraPathTest.php, Gemini/tests/Islandora/Gemini/Tests/GetDrupalPathTest.php, Gemini/tests/Islandora/Gemini/Tests/GetFedoraPathTest.php, composer.json
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/566
Will be smaller after https://github.com/Islandora-CLAW/Crayfish/pull/16 lands, as Hypercube shouldn't be included in the diff then.
Adds a path mapping service to Crayfish.  It's not quite a uri mapping service as per https://github.com/Islandora-CLAW/CLAW/issues/566, it's the part after the base url that gets mapped.  This is to account for Fedora's behaviour with Host headers.
A Silex microservice to align paths between similar objects in Drupal and Fedora.  It will be used extensively by the sync machinery in Alpaca.  It runs off of mysql using Doctrine's database abstraction layer.  See the README for more details.
Try the commands described in the README with cURL or use a client like Postman to test it …
=> Add gemini

.gitignore, Houdini/README.md, Houdini/cfg/cfg.php, Houdini/composer.json, Houdini/composer.lock, Houdini/phpunit.xml.dist, Houdini/src/Controller/HoudiniController.php, Houdini/src/app.php, Houdini/src/index.php, Houdini/tests/Islandora/Houdini/Tests/HoudiniControllerTest.php, README.md
Resolves:
https://github.com/Islandora-CLAW/CLAW/issues/577
Add a new service for transforming images using imagemagick.
- Get a JWT.  I added a dsm [here](https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/src/Plugin/RulesAction/Broadcaster.php#L122) and then performed a write operation on a FedoraResource to print it to the page.
- Use an HTTP client like Postman, making sure to add your token as an Authorization header for both of the following requests.
- Add a image to Fedora as a NonRdfSource at `http://localhost:8080/fcrepo/rest/some/crazy/path`
- Run the builtin webserver with `php -S localhost:8088 -t /path/to/Houdini/src`
- Request the identify JSON for the image sending a GET request to Houdini at `http://localhost:8088/identify/some/crazy/path`
- Request a converted …
=> Add a new service Houdini

Gemini/.gitignore, Gemini/cfg/cfg.php, Gemini/composer.json, Gemini/composer.lock, Gemini/src/Controller/GeminiController.php, Gemini/src/app.php, Gemini/tests/Islandora/Gemini/Tests/CreatePairTest.php, Houdini/cfg/cfg.php, Houdini/composer.lock, Hypercube/cfg/cfg.php, Hypercube/composer.json, Hypercube/composer.lock, Hypercube/src/app.php, README.md
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/595
* Blocks https://github.com/Islandora-CLAW/claw_vagrant/pull/34
Updates Gemini and Hypercube to use the IslandoraServiceProvider so we get JWT auth and request logging.
Touch ups to composer.json files, cfg.php files, and app.php files.  Just enough to make it work with our awesome new IslandoraServiceProvider from Crayfish-Commons.
I also touched up the tests for Gemini since they were confusing.  Thanks to @whikloj for pointing that out.
If this passes review, it should be merged and https://github.com/Islandora-CLAW/claw_vagrant/pull/34 should be tested.
=> IslandoraServiceProvider update

Milliner/cfg/config.example.yaml, Milliner/composer.json, Milliner/src/Converter/DrupalEntityConverter.php, Milliner/tests/Islandora/Milliner/Tests/DrupalEntityConverterTest.php
This adds the ability to have drupal in a subdirectory (which is my current scenario)
The path that was being passed, via Milliner, to guzzle was absolute, so any path on the base_uri was then lost.
For example, if I my base path was `http://localhost/claw` and the drupal node was `/node/81`, the resulting uri would become `http://localhost/node/81` and not resolve.   This fixes that issue by making sure the leading slash is always removed from the drupal entity string. 
**GitHub Issue**: (link)
* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
This pull request removes a leading slash from the node path that will be used to talk to drupal with.  This way if the drupal_base_uri has a path on it the node being worked with will still …
=> Allows base_uri with path to function

Gemini/bin/console, Gemini/composer.json, Gemini/composer.lock, Gemini/src/Controller/GeminiController.php, Gemini/src/Migrations/Version20180530031926.php, Gemini/src/UrlMapper/UrlMapper.php, Gemini/src/console.php
**GitHub Issue**: (https://github.com/Islandora-CLAW/CLAW/issues/828)
Refactors Gemini (Fedora/Drupal URI Mapper) to use hash based primary keys (composite) in its DB.
This is still Silex until we move to Symfony.
I also added a Symfony/Console app. using Doctrine's Migrate model to allow Table creation (and keeping track of changes) using console app
New DB table schema includes 4 new fields, fedora_hash, drupal_hash, dateCreated and dateUpdated
* Does this change require documentation to be updated? No, all the public part was left as-IS
* Does this change add any new dependencies? yep, run composer install (or update if you are unsure about your PHP version)
* Does this change require any other modifications to be made to the repository 
Totally. Since Gemini is a deal breaker/repo-cms …
=> Issue 828: Refactor schema to allow smaller indexes

Gemini/src/Migrations/Version20180530031926.php
**GitHub Issue**: Islandora-CLAW/CLAW#722
Follow up to Islandora-CLAW/Crayfish/pull/46
Adds a postgres support for the Gemini migration.
Compares the installed db and issues the appropriate SQL command. Note that it now drops any existing Gemini db, so back it up before you use this. 
Same as Islandora-CLAW/Crayfish/pull/46 except with postgres!
- Pull or apply patch
- run composer install inside Gemini
- Make sure your working and existing config.yaml file is still there and it works
- run `php bin/console list` to see available commands
- run `php bin/console migrations:migrate` which will trigger a Migration file.
@DiegoPino  @Islandora-CLAW/committers
=> add postgresql migration

README.md
**GitHub Issue**: Part of Islandora-CLAW/CLAW#950
Updates the Travis badge in README.md to point to the new travis-ci.com
=> Pointing travis badge to .com instead of .org

Gemini/composer.lock, Homarus/composer.lock, Houdini/composer.lock, Milliner/composer.lock
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/981
Updates compser.lock files so we get the newest crayfish-commons code (and other dependencies).  This should stop the auth errors we're experiencing in https://github.com/Islandora-CLAW/CLAW/issues/981
1. Pull this PR to your Crayfish installation
2. Go into each microservice and run `composer install` to use the new lock file and get new dependencies
3. Check and see if derivatives work again.
=> Updating lock files

Homarus/cfg/config.example.yaml, Homarus/src/Controller/HomarusController.php
**GitHub Issue**: (link)
* https://github.com/Islandora-CLAW/CLAW/issues/930
This PR adds configuration to enable creation of audio derivative files using Homarus/ffmpeg.  
* claw-playbook `vagrant up` with this PR: https://github.com/Islandora-Devops/ansible-role-crayfish/pull/18
The easiest way to test this component alone would be to replace the following with the ones in the PR.  
* Homarus/src/Controller/HomarusController.php
Create an audio file in Fedora.  Then issue the following curl command:
```
curl -H "Authorization: Bearer islandora" -H "Accept: audio/mpeg" -H "X-Islandora-Args: -codec:a libmp3lame -q:a 5" -H "Apix-Ldp-Resource:http://localhost:8080/fcrepo/rest/2019-02/input3.wav" http://localhost:8000/homarus/convert --output output.mp3
```
@dannylamb 
@MarcusBarnes …
=> support audio formats

Gemini/composer.lock, Homarus/composer.lock, Houdini/composer.lock, Hypercube/composer.lock, Milliner/composer.lock, Milliner/src/Service/MillinerService.php, Milliner/tests/Islandora/Milliner/Tests/DeleteTest.php, Milliner/tests/Islandora/Milliner/Tests/SaveMediaTest.php, Milliner/tests/Islandora/Milliner/Tests/SaveNodeTest.php, Recast/composer.lock
Fix Milliner tests relying on dead classes
**GitHub Issue**: n/a
Follow-up to https://github.com/Islandora-CLAW/Crayfish-Commons/pull/24 as Crayfish services all rely on `islandora/crayfish-commons:dev-master`. 
As a follow on to this (say not on a Friday) we probably should cut a `0.1` release of Crayfish-Commons and change all the services here from `islandora/crayfish-commons:dev-master` to `islandora/crayfish-commons:^0.1`
Updates lock files and fixes test fixtures.
Really updates the crayfish-commons version which updates the chullo version.
* Does this change require documentation to be updated? no
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change …
=> Update lock files for crayfish using newer chullo

Recast/README.md, Recast/cfg/config.example.yaml, Recast/src/Controller/RecastController.php, Recast/tests/RecastControllerTests.php, Recast/tests/resources/drupal_image.ttl
**GitHub Issue**: n/a Follow of on https://github.com/Islandora-CLAW/Crayfish/pull/44
This PR fixes the issue identified by @dannylamb in [this comment](https://github.com/Islandora-CLAW/Crayfish/pull/44#issuecomment-461831312)
Items with prefix mappings unknown to EasyRdf end up with default prefixes (ns0, ns1, ns2, etc)
This allows a user to add prefix/URI mappings to the recast service and have them appear.
* Does this change require documentation to be updated? yes, included
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no
Prior to this PR any resource transformed would get anonymous prefixes for things in the …
=> Fix undefined prefixes

Recast/src/Controller/RecastController.php, Recast/tests/RecastControllerTests.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1114 & https://github.com/Islandora-CLAW/CLAW/issues/1115
In Recast:
When parsing graphs of NonRDFSource descriptions we need to get the correct URI to parse it. This PR checks for a `Link: <http://localhost:8080/fcrepo/rest/binary>; rel="describes"` header and returns the URI so the graph is correct.
* Does this change require documentation to be updated? no
* Does this change add any new dependencies?  no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no
Use Recast and see the examples in the above tickets, pull in this PR and see that the graph has the correct subject.
Any additional information …
=> Use describes URI if it exists

Milliner/cfg/config.example.yaml, Milliner/src/Service/MillinerService.php, Milliner/src/app.php, Milliner/tests/Islandora/Milliner/Tests/DeleteTest.php, Milliner/tests/Islandora/Milliner/Tests/SaveExternalTest.php, Milliner/tests/Islandora/Milliner/Tests/SaveMediaTest.php, Milliner/tests/Islandora/Milliner/Tests/SaveNodeTest.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/887
Goes with:
- https://github.com/Islandora-CLAW/jsonld/pull/32
- https://github.com/Islandora-CLAW/islandora/pull/133
Supersedes:
- https://github.com/Islandora-CLAW/Crayfish/pull/65
**This is the same as https://github.com/Islandora-CLAW/Crayfish/pull/65, but on the Foundation's fork so we can test with the installer.**
Allows you to set a `strip_format_jsonld` configuration variable (false by default).  If set to true, `?_format=jsonld` will get stripped off before searching the jsonld when processing it.  This configuration should always be in alignment with the configuration in the `jsonld` module from https://github.com/Islandora-CLAW/jsonld/pull/32.  If it is out of alignment, when Milliner prepares the jsonld to go …
=>  Stripping _format=jsonld when configured to do so

Milliner/src/Service/MillinerService.php
**GitHub Issue**: Part of Islandora-CLAW/CLAW#662
Goes with https://github.com/Islandora-CLAW/islandora/pull/136 and https://github.com/Islandora-CLAW/islandora_demo/pull/29
Passes in the Drupal url from Gemini instead of trying to reconstruct it (which was brittle and failing) when saving RDF.  This way, nodes and media work the same, despite having very different subject urls.
See https://github.com/Islandora-CLAW/islandora/pull/136
@whikloj @Islandora-CLAW/committers
=> Using file url for media

Gemini/README.md
**Resolves**: https://github.com/Islandora-CLAW/CLAW/issues/1126
Adds documentation of the `/by_uri` Gemini endpoint.
Read docs, do they make sense?
@Islandora-CLAW/committers @kayakr
=> Add by_uri docs

Gemini/README.md, README.md
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1082
Replaces references to Islandora CLAW in readme files with "Islandora 8." Does not go any deeper into the code to hunt down CLAWs.
Islandora CLAW -> Islandora 8 in Crayfish readmes.
Review and make sure I got'em all. 
I know there's a lot more work to be done here with the branding and how deep "CLAW" has gotten into the stack, but this seems like low-hanging fruit that we might as well get out of the way so our public face is more consistent. 
First PR of many.
=> De-CLAWing readme files

.gitignore, .travis.yml, Gemini/composer.json, Gemini/composer.lock, Homarus/composer.json, Homarus/composer.lock, Houdini/composer.json, Houdini/composer.lock, Hypercube/composer.json, Hypercube/composer.lock, Milliner/composer.json, Milliner/composer.lock, Recast/composer.json, Recast/composer.lock
**GitHub Issue**: N/A
Still trying to get correct chullo into Crayfish related to #74 test failures
1. Update all lockfiles to PHP 7.2
1. Update chullo/crayfish-commons to dev branches
1. Update travis testing to remove 7.1 and add 7.3 as an allowed failure.
Travis really.
=> Add minimum-stability & prefer-stable to get chullo:dev

Hypercube/cfg/config.example.yaml, Hypercube/src/Controller/HypercubeController.php, Hypercube/src/app.php, Hypercube/tests/Islandora/Hypercube/Tests/HypercubeControllerTest.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/933
Adds pdftotext support for Hypercube.
Hypercube now checks the content type of the resource and uses pdftotext if it receives a PDF.
- `sudo apt-get install pdftotext`
- Pull this down into crayfish
- Update the `executable` entry in `config.yaml` to be `tesseract_executable` and `pdftotext_executable` as per `config.example.yaml`.
- Upload a PDF
- Hit hypercube with something like this: `curl -H "Authorization: Bearer islandora" -H "Apix-Ldp-Resource: http://localhost:8080/fcrepo/rest/2019-09/my-file.pdf" localhost:8000/hypercube/`
- Watch the lovely extracted text get blurted out onto your console.
Updated ansible role coming soon.
=> Adding pdftotext for PDF support in Hypercube

Homarus/cfg/config.example.yaml
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1298
Allow Homarus to generate PNG audio thumbnails by adding `image/png` as allowable request content type and `image/png_image2pipe` as output target.
Homarus can generate jpeg thumbnails. This allows PNG thumbnails, as specified for thumbnailing of audio files.
* Apply this config to Homarus: `/var/www/html/Crayfish/Homarus/cfg/config.yaml`
* Add 'Audio - Generate a thumbnail from an original file' action from https://github.com/Islandora-CLAW/CLAW/issues/1298
* Create a repository item with model=Audio, and Audio media with Use=Original file and upload a `.mp3` or `.wav` file.
* In Content administration, check the checkbox for the audio item, then select the action 'Audio - Generate a thumbnail from an original file' and …
=> Allow Homarus to generate PNG audio thumbnails

composer.json
**GitHub Issue**: Islandora/documentation#1267
Packagist sent me an email complaining about invalid composer.json.  I fixed it.
Removed a comma.
Merge this and I'll check if packagist is happy.
@Islandora/8-x-committers
=> Fixing invalid composer.json

Gemini/src/Controller/GeminiController.php, Gemini/src/UrlMinter/UrlMinter.php, Gemini/src/UrlMinter/UrlMinterInterface.php, Gemini/src/app.php, Gemini/tests/Islandora/Gemini/Tests/UrlMinterTest.php, Milliner/composer.json, Milliner/src/Controller/MillinerController.php, Milliner/src/Service/MillinerService.php, Milliner/src/Service/MillinerServiceInterface.php, Milliner/tests/Islandora/Milliner/Tests/DeleteTest.php, Milliner/tests/Islandora/Milliner/Tests/MillinerControllerTest.php, Milliner/tests/Islandora/Milliner/Tests/SaveExternalTest.php, Milliner/tests/Islandora/Milliner/Tests/SaveMediaTest.php, Milliner/tests/Islandora/Milliner/Tests/SaveNodeTest.php
** Please hold on from testing.  Will provide more info. **
**GitHub Issue**: (link)
Part of the work towards: https://github.com/Islandora/documentation/issues/926
This PR accepts fedora_end_point as header argument and uses it to create the fedora resource.
Dependency: https://github.com/Islandora/Alpaca/pull/65,https://github.com/Islandora/Crayfish-Commons/pull/36
Backup installed Gemini and Milliner
vagrant@claw:/var/www/html$ sudo cp -R Crayfish/Gemini/ ./
vagrant@claw:/var/www/html$ sudo cp -R Crayfish/Milliner/ ./
Delete Gemini and Milliner folders
vagrant@claw:/var/www/html/Crayfish$ rm -R Gemini
vagrant@claw:/var/www/html/Crayfish$ rm -R Milliner
Get the PR into a folder:
vagrant@claw:/var/www/html$ sudo mkdir CrayfishNew
vagrant@claw:/var/www/html/CrayfishNew$ sudo git clone …
=> Container name

Gemini/tests/Islandora/Gemini/Tests/UrlMinterTest.php, Homarus/src/Controller/HomarusController.php, Homarus/tests/Islandora/Homarus/Tests/HomarusControllerTest.php
**GitHub Issue**: Part of the fix for https://github.com/Islandora/documentation/issues/1278
Adds `-loglevel error` to every `ffmpeg` command so that large files can be processed. 
See https://github.com/Islandora/documentation/issues/1278
@Islandora/8-x-committers @kayakr @antbrown
=> Adding `-loglevel error` for large files

.travis.yml, CONTRIBUTING.md, Gemini/cfg/config.example.yaml, Gemini/composer.lock, Homarus/cfg/config.example.yaml, Homarus/composer.lock, Houdini/cfg/config.example.yaml, Hypercube/cfg/config.example.yaml, Hypercube/composer.lock, Milliner/cfg/config.example.yaml, Milliner/composer.lock, Milliner/src/Controller/MillinerController.php, Milliner/src/Service/MillinerService.php, Milliner/src/Service/MillinerServiceInterface.php, Milliner/src/app.php, Milliner/tests/Islandora/Milliner/Tests/CreateVersionTest.php, Milliner/tests/Islandora/Milliner/Tests/MillinerControllerTest.php, README.md, Recast/cfg/config.example.yaml, Recast/composer.lock, codecov.yml
**GitHub Issue**: (https://github.com/Islandora/documentation/issues/740)
* Other Relevant Links 
https://github.com/Islandora/Alpaca/pull/70
Allows Milliner to fire requests to Fedora to create versions of Media objects
* Separates the routes for node versioning and media versioning - because they rely on different data
* Abstracts shared code with the saveMedia method where possible to reduce duplication
* Creates a Fedora version for a Media object
* Bring in the related Alpaca PR here: https://github.com/Islandora/Alpaca/pull/70
* Clone/pull this PR into Milliner (in playbook - `/var/www/html/Crayfish/Milliner`)
* Create a repository item node (make sure it persists to Fedora)
* Edit the node - make sure it gets a version in Fedora - in Fedora UI or via API call
* Create a media …
=> Media versioning

Homarus/src/Controller/HomarusController.php
**GitHub Issue**: (https://github.com/Islandora/documentation/issues/1447)
FFMpeg had been failing on files that were not visible to anonymous viewers.  This adds token-based authentication.
Not much.  I grabbed the token from the incoming request object and jammed it (© Danny Lamb  ) into ffmpeg as a header.
Create an Audio media in a non-open filesystem.  A service file should generate.  If there are any problems you'll see them in the homarus.log
@Islandora/8-x-committers @Natkeeran @dannylamb
=> Added authorization.
